### ISSUE TITLE
关于生成yaml配置节点的问题

### ISSUE THREAD

**Issue by jaredtech** [YangLang116/iFlutter#10]
### 问题
Flutter添加同一个字体族(`family`)是使用下面这样的方式
```
fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
```

而iFlutter插件注册资源的形式却是把族(`family`)中每一种权重(`weight`)的文件生成一族，在配置全局字体时，如果使用了其他权重(`weight`)就无法生效。
### 建议

1. 在注册资源或者资源重置时，添加勾选项不清理指定yaml节点(如‘fonts’)
2. 在生成字体配置节点的时候，根据‘-’拆分出文件名前半段为族名，根据字体族(`family`)的名字(如‘Raleway-’)开头的字体文件配置放在同一个fonts节点下。

无奈对idea插件开发不熟，没法解决。
